[package]
name = "mdtui-tui"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Ratatui projectional Markdown editor prototype"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
image.workspace = true
mdtui-core = { path = "../mdtui-core" }
mdtui-markdown = { path = "../mdtui-markdown" }
mdtui-render = { path = "../mdtui-render" }
mdtui-terminal = { path = "../mdtui-terminal" }
ratatui.workspace = true
ratatui-image.workspace = true
serde.workspace = true
toml.workspace = true
tui-checkbox.workspace = true
tui-scrollview.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
